#!/bin/sh 


#$1 le nom du fichier à tester



echo "Generation du script commande ..."
bash script.sh $1 >> /dev/null
echo "terminée"
echo "Execution de gdb"
gdb $1 -x ./commands -q -batch >> /dev/null
echo "Génération du résultat.html"
./color
x-www-browser resultat.html
echo "fin" 
